server:
  port: 8080

spring:
  security:
    oauth2:
      client:
        registration:
          client-oidc:
            provider: spring
            client-id: client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid
            client-name: client-oidc
          client-authorization-code:
            provider: spring
            client-id: client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: articles.read
            client-name: client-authorization-code
        provider:
          spring:
            issuer-uri: http://auth-server:9000